clear_output: false
force_cpu: false
max_threads: 2
memory_limit: 0
memory_mode: smart
max_ram_gb: 0
max_vram_gb: 0
detect_pack_frame_count: 256
staged_chunk_size: 0
output_image_format: png
output_template: '{file}_{time}'
output_video_codec: libx264
output_video_format: mp4
provider: cuda
selected_theme: Default
server_name: ''
server_port: 0
server_share: true
video_quality: 14
video_swapping_method: Smart staged processing
